// lectures.js
const lectureVideos = [
  // ==========================================
  // PHYSICS WALLAH (PW) LECTURES
  // ==========================================
  {
    "title": "Physics One-Shots (PW)",
    "folders": ["LECTURES", "Physics", "Physics Wallah"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLxyGaR3hEy3gYPGsrnKx-XAi3yV6rocEx"
  },
  {
    "title": "Physical Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLxyGaR3hEy3hVmPjmool3j3U78cTYxYq-"
  },
  {
    "title": "Inorganic Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLxyGaR3hEy3hUTwPWVhqBOR0l_1o3vyCs"
  },
  {
    "title": "Organic Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLxyGaR3hEy3jWivnsFTb5uvzpHZK3qvDj"
  },
  {
    "title": "Mathematics (PW)",
    "folders": ["LECTURES", "Maths", "Physics Wallah"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLxyGaR3hEy3hJnlzYRfM6-sFuIEj0WRoC",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/Z5uGIO_11vM" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/uhq_WUNlvh8" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/DitLpxy6V48" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/FsTlbTQyuJ0" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/iLIPlvjDkPU" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/2YFQIFQmPmw" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/SOXQuRrgJHo" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/t_RMMkiYj4g" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/CVG9PcraP1k" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/Qs0wRt70mC4" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/rdWRwY2kEXI" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/rPFlUfjcakw" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/QMWDHOcXEQI" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/3JMzZR2TvhA" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/pufR8xp-CQA" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/7dVDuyI_8FA" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/qcpj3jjgr6o" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/Nv9s38ZGPes" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/UwRAUIeoCtI" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/fia_GxMeG7Q" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/H1FKKjz8hsw" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/zITyahKONeg" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/x0vMQRKTmQ0" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/ZdCd1G0NDUI" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/Q-AlaLN72w0" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/JnER25G1V7o" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/mWa7eSpT6kg" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/3OFuYbk-BV4" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/hsedtF2azNQ" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/jOVcucQLv38" }
    ]
  },
  // ==========================================
  // NEHA AGRAWAL LECTURES
  // ==========================================
  {
    "title": "JEE Maths Playlist 1 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLTa2m6WeLW_9Y10X7YJGR9A0j1RCMfPEr",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/VMlrlqJgWdQ" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/QIbRBtoAsjE" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/QWo-Uy7KRp4" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/XVZ20FDLorE" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/MnUt4uRiUv8" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/kTrZgk8ht6s" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/qMZbl49B2gk" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/1Px2H-ZNAXc" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/FjePwtMW_jA" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/aBuT_NpL4kM" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/bpeEpWjvG50" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/PbeylmdToTs" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/BbDh_D9NOAc" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/dZleU5ZUDAo" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/N1gW3lZx_4I" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/RHk11VC256Y" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/Se39Hv2_FzM" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/ze6pUWYfAvY" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/EO_6mXn9szs" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/WFY1D61ZOV0" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/IQeeRDA6T94" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/fvUETQWW34Y" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/KGI1PiPN-q4" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/p3R5yXcJdX4" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/q44atF--01U" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/H3ajZU-w1Mk" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/yZhWIgH-wqs" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/tVN2lZQV2_M" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/XHDRIk0UL0w" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/Zl53W-m0wTM" },
      { "title": "Lecture 31", "url": "https://www.youtube.com/embed/hhLxKrIj5b4" },
      { "title": "Lecture 32", "url": "https://www.youtube.com/embed/WPQzDvdJQak" },
      { "title": "Lecture 33", "url": "https://www.youtube.com/embed/K8fyaYIGtBE" },
      { "title": "Lecture 34", "url": "https://www.youtube.com/embed/IqiClz6TEiM" },
      { "title": "Lecture 35", "url": "https://www.youtube.com/embed/hezQFC6RJjs" },
      { "title": "Lecture 36", "url": "https://www.youtube.com/embed/LLxVhlleHRM" },
      { "title": "Lecture 37", "url": "https://www.youtube.com/embed/csb-IQN_pqU" },
      { "title": "Lecture 38", "url": "https://www.youtube.com/embed/FgILOHipMtw" },
      { "title": "Lecture 39", "url": "https://www.youtube.com/embed/D0hzgpe5L9s" },
      { "title": "Lecture 40", "url": "https://www.youtube.com/embed/Wr6MNW6itqo" }
    ]
  },
  {
    "title": "JEE Maths Playlist 2 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLTa2m6WeLW__n4j6kuZUVOA7hyljFKG6d",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/AVjdJITX0Nc" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/obx33lta9P4" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/Ui0P-tOC-f0" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/pouyY30rSHo" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/IKZ_2Z2OOBQ" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/--k01m3f5Cw" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/7HbfPG8pVhs" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/2DC7cdv43Ao" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/ryAw6vipopk" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/mjoCuNKUzB4" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/aSAg23ixuWE" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/2eOXSPy1MuE" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/4vagx7oH87k" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/aIjPAFSjRcI" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/0DJXH0ql7BI" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/JdHwa70kY3s" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/qcDGzbWSTjo" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/o07B71pxaBo" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/EJtgkGdqOgY" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/jUxPvBZAK_4" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/56Odj-FzH18" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/PTO6XHJfFU8" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/yMiEhnxQe8Y" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/dgUEfZohNJU" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/UI_SOsUZBJE" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/FJia0zLEq4U" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/Me9E0PFbuGQ" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/feBdaVYlkNs" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/kHj73PtXHQE" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/yZhWIgH-wqs" },
      { "title": "Lecture 31", "url": "https://www.youtube.com/embed/H3ajZU-w1Mk" },
      { "title": "Lecture 32", "url": "https://www.youtube.com/embed/FZJt1h-gO4w" },
      { "title": "Lecture 33", "url": "https://www.youtube.com/embed/mcMHaUuhe6o" },
      { "title": "Lecture 34", "url": "https://www.youtube.com/embed/UNOBGZjYiFk" },
      { "title": "Lecture 35", "url": "https://www.youtube.com/embed/mb_ZpNpL4Go" },
      { "title": "Lecture 36", "url": "https://www.youtube.com/embed/v8qnbEQulmA" },
      { "title": "Lecture 37", "url": "https://www.youtube.com/embed/vMGMYl00kJI" }
    ]
  },
  {
    "title": "JEE Maths Playlist 3 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLTa2m6WeLW__zL1AoV8uEG13xiQMj2RU8",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/j1pDmQJ0wOY" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/nfPvo7p-8t0" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/F0eIeAYiUUM" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/GNtYHAk_C4s" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/Q1AMRktu4pc" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/V3PYBhJS0Po" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/0Bul5m9fN_8" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/AmUO2o9NOYk" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/WvmEDNxgVxg" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/KUu18_pkvbk" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/C3DS0tqK2TY" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/BPgL5Xrp1LA" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/lkAPODbXnS0" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/Bk6PQ6huy68" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/Sh6yppz4nzs" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/HkBKPCNFZ4k" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/QS59lEJgPb8" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/u4Fu2PcRSo4" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/_P2GRAVyk_Q" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/LK0cQmgJsdk" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/MvTfxcM8hHs" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/fdfT1w9rVJQ" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/ct-vCt9NU08" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/cJceE7-8TBY" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/UJXel5_AOSY" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/GN9uAEisDtM" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/peKwXDIcYss" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/iaK4ukVmFvc" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/yP0EKKN0zys" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/7_ZpO1hneXk" },
      { "title": "Lecture 31", "url": "https://www.youtube.com/embed/TQX02-rVCsA" }
    ]
  },
  {
    "title": "JEE Maths Playlist 4 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLTa2m6WeLW_9ka56IJq29mHC07x1j6iIz"
  }
];
