// lectures.js

const lectureVideos = [
  // ==========================================
  // PHYSICS WALLAH (PW) LECTURES
  // ==========================================
  {
    "title": "Physics One-Shots (PW)",
    "folders": ["LECTURES", "Physics", "Physics Wallah"],
    "playlist": [
      { "title": "Basic Maths & Vectors", "url": "https://www.youtube.com/embed/RAwcPN79g0Q" },
      { "title": "Kinematics", "url": "https://www.youtube.com/embed/mpFEnSQpJ9Q" },
      { "title": "Laws of Motion", "url": "https://www.youtube.com/embed/6HQgDO1trlM" },
      { "title": "Work, Energy & Power", "url": "https://www.youtube.com/embed/XGce-vIcMfU" },
      { "title": "COM & Collision", "url": "https://www.youtube.com/embed/Rh95KkMwklU" },
      { "title": "Rotational Motion", "url": "https://www.youtube.com/embed/vmaKeSkjtGo" },
      { "title": "Gravitation", "url": "https://www.youtube.com/embed/mE8w2uxm6XY" },
      { "title": "Solids & Elasticity", "url": "https://www.youtube.com/embed/1xPm3vIRIGI" },
      { "title": "Fluid Mechanics", "url": "https://www.youtube.com/embed/griSf2U_Zlk" },
      { "title": "SHM", "url": "https://www.youtube.com/embed/myNQbAYzD5A" },
      { "title": "Wave Motion", "url": "https://www.youtube.com/embed/PAlXOkn_Pa8" },
      { "title": "Thermal Properties", "url": "https://www.youtube.com/embed/1nTFrbJ8Jhg" },
      { "title": "Thermodynamics & KTG", "url": "https://www.youtube.com/embed/Ch9jLsgYIuM" },
      { "title": "Electrostatics", "url": "https://www.youtube.com/embed/h5HIyPNRhqI" },
      { "title": "Capacitors", "url": "https://www.youtube.com/embed/FImh-a0673s" },
      { "title": "Current Electricity", "url": "https://www.youtube.com/embed/cjoRcywyRv0" },
      { "title": "Magnetism & Moving Charges", "url": "https://www.youtube.com/embed/3h3OexznsA0" },
      { "title": "Electromagnetic Induction", "url": "https://www.youtube.com/embed/ebOF14qP21k" },
      { "title": "AC Circuits", "url": "https://www.youtube.com/embed/gziRcxMiO_Q" },
      { "title": "Wave Optics & EM Waves", "url": "https://www.youtube.com/embed/UYfR15GpKIs" },
      { "title": "Ray Optics", "url": "https://www.youtube.com/embed/AfPD-sHayb0" },
      { "title": "Semiconductors", "url": "https://www.youtube.com/embed/5h5ANJnVe08" },
      { "title": "Communication Systems", "url": "https://www.youtube.com/embed/fBqJdix2NjE" },
      { "title": "Modern Physics", "url": "https://www.youtube.com/embed/G58QS4soCuQ" },
      { "title": "Atoms", "url": "https://www.youtube.com/embed/AqjrqRyot6w" },
      { "title": "Nuclei", "url": "https://www.youtube.com/embed/XJZ1PdXyJU4" },
      { "title": "Dual Nature", "url": "https://www.youtube.com/embed/wE0xrUuJLnk" }
    ]
  },
  {
    "title": "Physical Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "playlist": [
      { "title": "Mole Concept", "url": "https://www.youtube.com/embed/CAb8YZKLoac" },
      { "title": "Atomic Structure", "url": "https://www.youtube.com/embed/f6ENSghG7T4" },
      { "title": "States of Matter", "url": "https://www.youtube.com/embed/8oypjDXAXZc" },
      { "title": "Thermodynamics", "url": "https://www.youtube.com/embed/GplPceRaMi0" },
      { "title": "Chemical Equilibrium", "url": "https://www.youtube.com/embed/NwCmoh7Vd9g" },
      { "title": "Ionic Equilibrium", "url": "https://www.youtube.com/embed/BceSksiNLD4" },
      { "title": "Redox Reactions", "url": "https://www.youtube.com/embed/1W-UvePUAKo" },
      { "title": "Chemical Kinetics", "url": "https://www.youtube.com/embed/kwPNxC9AgZA" },
      { "title": "Solutions", "url": "https://www.youtube.com/embed/7OkNy8vhDaw" }
    ]
  },
  {
    "title": "Inorganic Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "playlist": [
      { "title": "Periodic Table", "url": "https://www.youtube.com/embed/nLE7_YBFQNQ" },
      { "title": "Chemical Bonding", "url": "https://www.youtube.com/embed/kS8s_WX0IlY" },
      { "title": "Coordination Compounds", "url": "https://www.youtube.com/embed/5myJzBeN514" },
      { "title": "P-Block Elements", "url": "https://www.youtube.com/embed/b0k5LOk_uPk" },
      { "title": "D & F-Block Elements", "url": "https://www.youtube.com/embed/SjILQ6cX_Vo" },
      { "title": "Salt Analysis", "url": "https://www.youtube.com/embed/8rRnn4ECwXI" }
    ]
  },
  {
    "title": "Organic Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "playlist": [
      { "title": "IUPAC Nomenclature", "url": "https://www.youtube.com/embed/A2QTsYu3fWo" },
      { "title": "GOC", "url": "https://www.youtube.com/embed/FFCT-lh86tA" },
      { "title": "Isomerism", "url": "https://www.youtube.com/embed/UOzWO2-Z9So" },
      { "title": "Hydrocarbons", "url": "https://www.youtube.com/embed/02CBTEOMMsA" },
      { "title": "Haloalkanes & Haloarenes", "url": "https://www.youtube.com/embed/7iJFvPI8vMM" },
      { "title": "Alcohols, Phenols & Ethers", "url": "https://www.youtube.com/embed/IDo8B0c5Xis" },
      { "title": "Aldehydes, Ketones & Acids", "url": "https://www.youtube.com/embed/oR19BqbPBu4" },
      { "title": "Amines", "url": "https://www.youtube.com/embed/SKHrfD34Kkc" },
      { "title": "Biomolecules", "url": "https://www.youtube.com/embed/LcVNwEWJtyI" }
    ]
  },
  {
    "title": "Mathematics (PW)",
    "folders": ["LECTURES", "Maths", "Physics Wallah"],
    "playlist": [
      { "title": "Basic Maths", "url": "https://www.youtube.com/embed/Z5uGIO_11vM" },
      { "title": "Determinants", "url": "https://www.youtube.com/embed/uhq_WUNlvh8" },
      { "title": "Trigonometric Ratios & Identities", "url": "https://www.youtube.com/embed/DitLpxy6V48" },
      { "title": "Vectors", "url": "https://www.youtube.com/embed/FsTlbTQyuJ0" },
      { "title": "Quadratic Equations", "url": "https://www.youtube.com/embed/iLIPlvjDkPU" },
      { "title": "Matrices", "url": "https://www.youtube.com/embed/2YFQIFQmPmw" },
      { "title": "Sets", "url": "https://www.youtube.com/embed/SOXQuRrgJHo" },
      { "title": "3D Geometry", "url": "https://www.youtube.com/embed/t_RMMkiYj4g" },
      { "title": "Sequence & Series", "url": "https://www.youtube.com/embed/CVG9PcraP1k" },
      { "title": "Relations & Functions", "url": "https://www.youtube.com/embed/Qs0wRt70mC4" },
      { "title": "Inverse Trigonometric Functions", "url": "https://www.youtube.com/embed/rdWRwY2kEXI" },
      { "title": "Permutation & Combination", "url": "https://www.youtube.com/embed/rPFlUfjcakw" },
      { "title": "Binomial Theorem", "url": "https://www.youtube.com/embed/QMWDHOcXEQI" },
      { "title": "Method of Differentiation", "url": "https://www.youtube.com/embed/3JMzZR2TvhA" },
      { "title": "Straight Lines", "url": "https://www.youtube.com/embed/pufR8xp-CQA" },
      { "title": "Indefinite Integration", "url": "https://www.youtube.com/embed/7dVDuyI_8FA" },
      { "title": "Circles", "url": "https://www.youtube.com/embed/qcpj3jjgr6o" },
      { "title": "Parabola", "url": "https://www.youtube.com/embed/Nv9s38ZGPes" },
      { "title": "Definite Integration", "url": "https://www.youtube.com/embed/UwRAUIeoCtI" },
      { "title": "Differential Equation", "url": "https://www.youtube.com/embed/H1FKKjz8hsw" },
      { "title": "Hyperbola", "url": "https://www.youtube.com/embed/zITyahKONeg" },
      { "title": "Application of Integrals", "url": "https://www.youtube.com/embed/x0vMQRKTmQ0" },
      { "title": "Ellipse", "url": "https://www.youtube.com/embed/ZdCd1G0NDUI" },
      { "title": "Complex Number", "url": "https://www.youtube.com/embed/Q-AlaLN72w0" },
      { "title": "Limits", "url": "https://www.youtube.com/embed/JnER25G1V7o" },
      { "title": "Statistics", "url": "https://www.youtube.com/embed/mWa7eSpT6kg" },
      { "title": "Probability", "url": "https://www.youtube.com/embed/3OFuYbk-BV4" },
      { "title": "Continuity & Differentiability", "url": "https://www.youtube.com/embed/hsedtF2azNQ" },
      { "title": "Application of Derivatives", "url": "https://www.youtube.com/embed/jOVcucQLv38" }
    ]
  },

  // ==========================================
  // NEHA AGRAWAL LECTURES
  // ==========================================
  {
    "title": "JEE Maths Playlist 1 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "playlist": [
      { "title": "Sequences & Series 3.0", "url": "https://www.youtube.com/embed/VMlrlqJgWdQ" },
      { "title": "Matrices & Determinants 3.0", "url": "https://www.youtube.com/embed/QIbRBtoAsjE" },
      { "title": "Vectors & 3D Geometry 3.0", "url": "https://www.youtube.com/embed/QWo-Uy7KRp4" },
      { "title": "Complex Numbers 3.0", "url": "https://www.youtube.com/embed/XVZ20FDLorE" },
      { "title": "Quadratic Equations 3.0", "url": "https://www.youtube.com/embed/MnUt4uRiUv8" },
      { "title": "Binomial Theorem 3.0", "url": "https://www.youtube.com/embed/kTrZgk8ht6s" },
      { "title": "Functions 3.0", "url": "https://www.youtube.com/embed/qMZbl49B2gk" },
      { "title": "Limits, Continuity & Derivatives 3.0", "url": "https://www.youtube.com/embed/1Px2H-ZNAXc" },
      { "title": "Application of Derivatives 3.0", "url": "https://www.youtube.com/embed/FjePwtMW_jA" },
      { "title": "Indefinite Integration 3.0", "url": "https://www.youtube.com/embed/aBuT_NpL4kM" },
      { "title": "Definite Integration 3.0", "url": "https://www.youtube.com/embed/bpeEpWjvG50" },
      { "title": "Differential Equations 3.0", "url": "https://www.youtube.com/embed/PbeylmdToTs" },
      { "title": "Sets & Relations 3.0", "url": "https://www.youtube.com/embed/BbDh_D9NOAc" },
      { "title": "Permutations & Combinations 3.0", "url": "https://www.youtube.com/embed/dZleU5ZUDAo" },
      { "title": "Probability 3.0", "url": "https://www.youtube.com/embed/N1gW3lZx_4I" },
      { "title": "Straight Lines 3.0", "url": "https://www.youtube.com/embed/RHk11VC256Y" },
      { "title": "Circles 3.0", "url": "https://www.youtube.com/embed/Se39Hv2_FzM" },
      { "title": "Conic Sections One Shot", "url": "https://www.youtube.com/embed/ze6pUWYfAvY" },
      { "title": "Inverse Trigonometry 3.0", "url": "https://www.youtube.com/embed/EO_6mXn9szs" },
      { "title": "Statistics 3.0", "url": "https://www.youtube.com/embed/WFY1D61ZOV0" },
      { "title": "Trigonometry & Inverse Trigonometry 3.0", "url": "https://www.youtube.com/embed/IQeeRDA6T94" },
      { "title": "Make Your Math Superstrong Topics", "url": "https://www.youtube.com/embed/fvUETQWW34Y" },
      { "title": "Differential Equations & Area Under Curve", "url": "https://www.youtube.com/embed/KGI1PiPN-q4" },
      { "title": "5 Easiest Chapters Math Marathon Part 1", "url": "https://www.youtube.com/embed/p3R5yXcJdX4" },
      { "title": "5 Easiest Chapters Math Marathon Part 2", "url": "https://www.youtube.com/embed/q44atF--01U" },
      { "title": "Complete Formula Revision Class 11", "url": "https://www.youtube.com/embed/H3ajZU-w1Mk" },
      { "title": "Complete Formula Revision Class 12", "url": "https://www.youtube.com/embed/yZhWIgH-wqs" },
      { "title": "Math Super Shortcuts & Tricks", "url": "https://www.youtube.com/embed/tVN2lZQV2_M" },
      { "title": "JEE Jan '24 PYQs with Shortcuts", "url": "https://www.youtube.com/embed/XHDRIk0UL0w" },
      { "title": "15 Sureshot Topics Math Marathon", "url": "https://www.youtube.com/embed/Zl53W-m0wTM" },
      { "title": "65 Topics (High Priority) for 99.5%ile", "url": "https://www.youtube.com/embed/hhLxKrIj5b4" },
      { "title": "JEE 2025 Final Push Game Changer", "url": "https://www.youtube.com/embed/WPQzDvdJQak" },
      { "title": "Calculus Booster Sprint", "url": "https://www.youtube.com/embed/K8fyaYIGtBE" },
      { "title": "Code 301: Save Your 1st Attempt", "url": "https://www.youtube.com/embed/IqiClz6TEiM" },
      { "title": "Vectors & 3D Booster Sprint", "url": "https://www.youtube.com/embed/hezQFC6RJjs" },
      { "title": "Algebra Revision Sprint", "url": "https://www.youtube.com/embed/LLxVhlleHRM" },
      { "title": "Coordinate Geometry Revision Sprint", "url": "https://www.youtube.com/embed/csb-IQN_pqU" },
      { "title": "60 Most Repeated Ques by NTA", "url": "https://www.youtube.com/embed/FgILOHipMtw" },
      { "title": "JEE Jan 2025 Math Marathon", "url": "https://www.youtube.com/embed/D0hzgpe5L9s" },
      { "title": "JEE Apr 2025 Analysis of All 10 Shifts", "url": "https://www.youtube.com/embed/Wr6MNW6itqo" }
    ]
  },
  {
    "title": "JEE Maths Playlist 2 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "playlist": [
      { "title": "Agni Series: Sequences & Series", "url": "https://www.youtube.com/embed/AVjdJITX0Nc" },
      { "title": "Agni Series: Matrices & Determinants", "url": "https://www.youtube.com/embed/obx33lta9P4" },
      { "title": "Agni Series: Vectors & 3D Geometry", "url": "https://www.youtube.com/embed/Ui0P-tOC-f0" },
      { "title": "Agni Series: Quadratic Equations & Complex Nos", "url": "https://www.youtube.com/embed/pouyY30rSHo" },
      { "title": "Agni Series: Binomial Theorem", "url": "https://www.youtube.com/embed/IKZ_2Z2OOBQ" },
      { "title": "Agni Series: Permutations & Combinations + Probability", "url": "https://www.youtube.com/embed/--k01m3f5Cw" },
      { "title": "Agni Series: Sets, Relations & Functions", "url": "https://www.youtube.com/embed/7HbfPG8pVhs" },
      { "title": "Agni Series: Trigonometry & Statistics", "url": "https://www.youtube.com/embed/2DC7cdv43Ao" },
      { "title": "Agni Series: Limits, Continuity & Derivatives + AOD", "url": "https://www.youtube.com/embed/ryAw6vipopk" },
      { "title": "Agni Series: Integration", "url": "https://www.youtube.com/embed/mjoCuNKUzB4" },
      { "title": "Agni Series: Differential Equations & Area", "url": "https://www.youtube.com/embed/aSAg23ixuWE" },
      { "title": "Agni Series: Straight Lines & Circles", "url": "https://www.youtube.com/embed/2eOXSPy1MuE" },
      { "title": "Agni Series: Conic Sections", "url": "https://www.youtube.com/embed/4vagx7oH87k" },
      { "title": "100 Days Timetable for JEE 2026", "url": "https://www.youtube.com/embed/aIjPAFSjRcI" },
      { "title": "Agni Series: Sequences & Series (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/0DJXH0ql7BI" },
      { "title": "Agni Series: Matrices & Determinants (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/JdHwa70kY3s" },
      { "title": "Agni Series: Trigonometry & Inverse + Statistics (Jan 2025)", "url": "https://www.youtube.com/embed/qcDGzbWSTjo" },
      { "title": "Agni Series: Sets, Relations & Functions (Jan 2025)", "url": "https://www.youtube.com/embed/o07B71pxaBo" },
      { "title": "Agni Series: Complex Numbers & Quadratic Eqns (Jan 2025)", "url": "https://www.youtube.com/embed/EJtgkGdqOgY" },
      { "title": "Agni Series: Permutations & Combinations + Probability (Jan 2025)", "url": "https://www.youtube.com/embed/jUxPvBZAK_4" },
      { "title": "Agni Series: Binomial Theorem (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/56Odj-FzH18" },
      { "title": "Agni Series: Limits, Continuity & Derivatives (Jan 2025)", "url": "https://www.youtube.com/embed/PTO6XHJfFU8" },
      { "title": "Agni Series: AOD & Area Under Curve (Jan 2025)", "url": "https://www.youtube.com/embed/yMiEhnxQe8Y" },
      { "title": "Agni Series: Integration (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/dgUEfZohNJU" },
      { "title": "Agni Series: Vectors (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/UI_SOsUZBJE" },
      { "title": "Agni Series: 3D Geometry (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/FJia0zLEq4U" },
      { "title": "Agni Series: Straight Lines (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/Me9E0PFbuGQ" },
      { "title": "Agni Series: Parabola (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/feBdaVYlkNs" },
      { "title": "Agni Series: Circles, Ellipse & Hyperbola (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/kHj73PtXHQE" },
      { "title": "Complete Formula Revision Class 12", "url": "https://www.youtube.com/embed/yZhWIgH-wqs" },
      { "title": "Complete Formula Revision Class 11", "url": "https://www.youtube.com/embed/H3ajZU-w1Mk" },
      { "title": "100 Most Repeated Math PYQs Last 7 Years", "url": "https://www.youtube.com/embed/FZJt1h-gO4w" },
      { "title": "Booster: 7 Easiest Chapters = 36+ Marks", "url": "https://www.youtube.com/embed/mcMHaUuhe6o" },
      { "title": "Booster: 67 Most Asked Topics by NTA", "url": "https://www.youtube.com/embed/UNOBGZjYiFk" },
      { "title": "Booster: 6 Highest Weightage Chapters = 48+ Marks", "url": "https://www.youtube.com/embed/mb_ZpNpL4Go" },
      { "title": "Math Marathon: Most Trending Topics & PYQs", "url": "https://www.youtube.com/embed/v8qnbEQulmA" },
      { "title": "100 Most Asked Questions by NTA", "url": "https://www.youtube.com/embed/vMGMYl00kJI" }
    ]
  },
  {
    "title": "JEE Maths Playlist 3 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "playlist": [
      { "title": "Logarithms | Beginner's Course", "url": "https://www.youtube.com/embed/j1pDmQJ0wOY" },
      { "title": "Trigonometry | Beginner's Course", "url": "https://www.youtube.com/embed/nfPvo7p-8t0" },
      { "title": "Inequalities : Wavy Curve | Beginner's Course", "url": "https://www.youtube.com/embed/F0eIeAYiUUM" },
      { "title": "Functions Basics, Domain & Range | Beginner's Course", "url": "https://www.youtube.com/embed/GNtYHAk_C4s" },
      { "title": "Modulus & Greatest Integer Functions | Beginner's Course", "url": "https://www.youtube.com/embed/Q1AMRktu4pc" },
      { "title": "Transformation of Graphs | Beginner's Course", "url": "https://www.youtube.com/embed/V3PYBhJS0Po" },
      { "title": "Complex Numbers | Beginner's Course", "url": "https://www.youtube.com/embed/0Bul5m9fN_8" },
      { "title": "Sequences & Series | Beginner's Course", "url": "https://www.youtube.com/embed/AmUO2o9NOYk" },
      { "title": "Limits with Tricks | Beginner's Course", "url": "https://www.youtube.com/embed/WvmEDNxgVxg" },
      { "title": "Differentiation | Beginner's Course", "url": "https://www.youtube.com/embed/KUu18_pkvbk" },
      { "title": "Integration | Beginner's Course", "url": "https://www.youtube.com/embed/C3DS0tqK2TY" },
      { "title": "Vectors | Beginner's Course", "url": "https://www.youtube.com/embed/BPgL5Xrp1LA" },
      { "title": "Matrices and Determinants | Beginner's Course", "url": "https://www.youtube.com/embed/lkAPODbXnS0" },
      { "title": "Binomial Theorem | Beginner's Course", "url": "https://www.youtube.com/embed/Bk6PQ6huy68" },
      { "title": "Permutations and Combinations | Beginner's Course", "url": "https://www.youtube.com/embed/Sh6yppz4nzs" },
      { "title": "Probability | Beginner's Course", "url": "https://www.youtube.com/embed/HkBKPCNFZ4k" },
      { "title": "Straight Lines | Beginner's Course", "url": "https://www.youtube.com/embed/QS59lEJgPb8" },
      { "title": "Conic Sections | Beginner's Course", "url": "https://www.youtube.com/embed/u4Fu2PcRSo4" },
      { "title": "Quadratic Equations | Beginner's Course", "url": "https://www.youtube.com/embed/_P2GRAVyk_Q" },
      { "title": "Sets | Beginner's Course", "url": "https://www.youtube.com/embed/LK0cQmgJsdk" },
      { "title": "Relations | Beginner's Course", "url": "https://www.youtube.com/embed/MvTfxcM8hHs" },
      { "title": "3D Geometry | Beginner's Course", "url": "https://www.youtube.com/embed/fdfT1w9rVJQ" }
    ]
  },
  {
    "title": "JEE Maths Playlist 4 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "playlist": [
      { "title": "Differentiation | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/ct-vCt9NU08" },
      { "title": "Logarithms | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/cJceE7-8TBY" },
      { "title": "Linear Inequalities & Wavy Curve | Foundation Series", "url": "https://www.youtube.com/embed/UJXel5_AOSY" },
      { "title": "Trigonometry | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/GN9uAEisDtM" },
      { "title": "Functions - Domain & Range | Foundation Series", "url": "https://www.youtube.com/embed/peKwXDIcYss" },
      { "title": "Integration | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/iaK4ukVmFvc" },
      { "title": "Sequences and Series | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/yP0EKKN0zys" },
      { "title": "Probability | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/7_ZpO1hneXk" },
      { "title": "Complete Class 11 Maths Required for Class 12 & JEE", "url": "https://www.youtube.com/embed/TQX02-rVCsA" }
    ]
  },

  // ==========================================
  // EDUNITI PHYSICS (MOHIT SIR)
  // ==========================================
  {
    "title": "Eduniti Physics Sure Shot (Mohit Sir)",
    "folders": ["LECTURES", "Physics", "Eduniti"],
    "playlist": [
      { "title": "Kinematics 2D", "url": "https://www.youtube.com/embed/_d0XU35l5jY" },
      { "title": "NLM", "url": "https://www.youtube.com/embed/lKgWBOMWdVU" },
      { "title": "Mechanics Concepts", "url": "https://www.youtube.com/embed/pg2FdPiWeCk" },
      { "title": "Mechanics P1", "url": "https://www.youtube.com/embed/3vkFbQxEYqE" },
      { "title": "Mechanics P2", "url": "https://www.youtube.com/embed/JJMhkssd4GQ" },
      { "title": "Mechanics P3", "url": "https://www.youtube.com/embed/Qbb6H6MhmRc" },
      { "title": "Pulley Block Cases", "url": "https://www.youtube.com/embed/t_2p18RSLXQ" },
      { "title": "VCM Sure Shot", "url": "https://www.youtube.com/embed/EwOMzB63gBI" },
      { "title": "Gravitation", "url": "https://www.youtube.com/embed/xF9ysyykedw" },
      { "title": "Rotation P1", "url": "https://www.youtube.com/embed/Q8Rujg2Mkio" },
      { "title": "SHM", "url": "https://www.youtube.com/embed/t7-G5GEfQXI" },
      { "title": "Thermodynamics Graphs", "url": "https://www.youtube.com/embed/IySVKH_OttE" },
      { "title": "Cylinder Piston", "url": "https://www.youtube.com/embed/0Ro_F6Af0Zg" },
      { "title": "Fluids P1", "url": "https://www.youtube.com/embed/gwC-whA3M3g" },
      { "title": "Fluids P2", "url": "https://www.youtube.com/embed/LIp4AZu3P0g" },
      { "title": "Wave Motion", "url": "https://www.youtube.com/embed/4ioZfE3kGMg" },
      { "title": "Electrostatics P1", "url": "https://www.youtube.com/embed/gf75PPW10oI" },
      { "title": "Electrostatics P2", "url": "https://www.youtube.com/embed/MqeFMKAf5x8" },
      { "title": "Electric Dipoles", "url": "https://www.youtube.com/embed/NKO1Szf4otc" },
      { "title": "Capacitors", "url": "https://www.youtube.com/embed/qx-CMGn2ud4" },
      { "title": "Circuits", "url": "https://www.youtube.com/embed/ie81MM1V4mE" },
      { "title": "Electrodynamics P1", "url": "https://www.youtube.com/embed/lllAWLu5mso" },
      { "title": "Electrodynamics P2", "url": "https://www.youtube.com/embed/1RdDchv2j_o" },
      { "title": "Physics Concepts Marathon", "url": "https://www.youtube.com/embed/2qGiA1vKwjg" },
      { "title": "Charge in Magnetic/Electric Field", "url": "https://www.youtube.com/embed/YmQvWuXsNhs" },
      { "title": "Magnetic Effect P1", "url": "https://www.youtube.com/embed/XBMDnZPLd90" },
      { "title": "Cavity Problem", "url": "https://www.youtube.com/embed/JcEaz2o0sL4" },
      { "title": "MEC Rank Decider", "url": "https://www.youtube.com/embed/2fhxJ9ukudY" },
      { "title": "Alternating Current", "url": "https://www.youtube.com/embed/H_9Pl8HeZ-o" },
      { "title": "Wave Optics/YDSE", "url": "https://www.youtube.com/embed/Wzi1hBDiyVo" },
      { "title": "Ray Optics Reflection/Refraction", "url": "https://www.youtube.com/embed/3Wmsf3lI73Y" },
      { "title": "Image Velocity", "url": "https://www.youtube.com/embed/X1_c_4JaNwU" },
      { "title": "Fish Bird Problem", "url": "https://www.youtube.com/embed/UTUyY5a9G3Y" },
      { "title": "Ray Optics Sure Shot", "url": "https://www.youtube.com/embed/FXJO4GYTmXI" },
      { "title": "Binding Energy", "url": "https://www.youtube.com/embed/5Tb_8wHchbU" },
      { "title": "Modern Physics", "url": "https://www.youtube.com/embed/MWJdpWvwhwc" },
      { "title": "Energy Conservation Cases", "url": "https://www.youtube.com/embed/_xOTxiWGGpI" },
      { "title": "Assertion Reason P1", "url": "https://www.youtube.com/embed/jka_UoZPqHs" },
      { "title": "Assertion Reason P2", "url": "https://www.youtube.com/embed/lauuB4VKWw4" },
      { "title": "Mixed Concepts P1", "url": "https://www.youtube.com/embed/vHIhXfilkpg" },
      { "title": "Mixed Concepts P2", "url": "https://www.youtube.com/embed/sdnEI-mpV4Y" },
      { "title": "Competency Based Questions", "url": "https://www.youtube.com/embed/U7xuWZaYJ0M" }
    ]
  }
];
