// lectures.js
const lectureVideos = [
  // ==========================================
  // PHYSICS WALLAH (PW) LECTURES
  // ==========================================
  {
    "title": "Physics One-Shots (PW)",
    "folders": ["LECTURES", "Physics", "Physics Wallah"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLxyGaR3hEy3gYPGsrnKx-XAi3yV6rocEx",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/RAwcPN79g0Q" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/mpFEnSQpJ9Q" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/6HQgDO1trlM" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/XGce-vIcMfU" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/Rh95KkMwklU" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/vmaKeSkjtGo" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/mE8w2uxm6XY" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/1xPm3vIRIGI" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/griSf2U_Zlk" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/myNQbAYzD5A" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/PAlXOkn_Pa8" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/1nTFrbJ8Jhg" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/Ch9jLsgYIuM" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/h5HIyPNRhqI" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/FImh-a0673s" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/cjoRcywyRv0" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/3h3OexznsA0" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/ebOF14qP21k" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/gziRcxMiO_Q" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/UYfR15GpKIs" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/AfPD-sHayb0" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/5h5ANJnVe08" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/fBqJdix2NjE" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/G58QS4soCuQ" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/AqjrqRyot6w" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/XJZ1PdXyJU4" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/wE0xrUuJLnk" }
    ]
  },
  {
    "title": "Physical Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLxyGaR3hEy3hVmPjmool3j3U78cTYxYq-",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/CAb8YZKLoac" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/f6ENSghG7T4" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/8oypjDXAXZc" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/GplPceRaMi0" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/NwCmoh7Vd9g" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/BceSksiNLD4" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/1W-UvePUAKo" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/kwPNxC9AgZA" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/7OkNy8vhDaw" }
    ]
  },
  {
    "title": "Inorganic Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLxyGaR3hEy3hUTwPWVhqBOR0l_1o3vyCs",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/nLE7_YBFQNQ" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/kS8s_WX0IlY" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/5myJzBeN514" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/b0k5LOk_uPk" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/SjILQ6cX_Vo" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/8rRnn4ECwXI" }
    ]
  },
  {
    "title": "Organic Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLxyGaR3hEy3jWivnsFTb5uvzpHZK3qvDj",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/A2QTsYu3fWo" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/FFCT-lh86tA" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/UOzWO2-Z9So" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/02CBTEOMMsA" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/7iJFvPI8vMM" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/IDo8B0c5Xis" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/oR19BqbPBu4" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/SKHrfD34Kkc" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/LcVNwEWJtyI" }
    ]
  },
  {
    "title": "Mathematics (PW)",
    "folders": ["LECTURES", "Maths", "Physics Wallah"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLxyGaR3hEy3hJnlzYRfM6-sFuIEj0WRoC",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/Z5uGIO_11vM" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/uhq_WUNlvh8" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/DitLpxy6V48" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/FsTlbTQyuJ0" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/iLIPlvjDkPU" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/2YFQIFQmPmw" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/SOXQuRrgJHo" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/t_RMMkiYj4g" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/CVG9PcraP1k" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/Qs0wRt70mC4" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/rdWRwY2kEXI" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/rPFlUfjcakw" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/QMWDHOcXEQI" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/3JMzZR2TvhA" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/pufR8xp-CQA" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/7dVDuyI_8FA" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/qcpj3jjgr6o" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/Nv9s38ZGPes" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/UwRAUIeoCtI" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/fia_GxMeG7Q" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/H1FKKjz8hsw" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/zITyahKONeg" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/x0vMQRKTmQ0" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/ZdCd1G0NDUI" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/Q-AlaLN72w0" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/JnER25G1V7o" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/mWa7eSpT6kg" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/3OFuYbk-BV4" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/hsedtF2azNQ" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/jOVcucQLv38" }
    ]
  },
  // ==========================================
  // NEHA AGRAWAL LECTURES
  // ==========================================
  {
    "title": "JEE Maths Playlist 1 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLTa2m6WeLW_9Y10X7YJGR9A0j1RCMfPEr",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/VMlrlqJgWdQ" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/QIbRBtoAsjE" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/QWo-Uy7KRp4" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/XVZ20FDLorE" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/MnUt4uRiUv8" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/kTrZgk8ht6s" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/qMZbl49B2gk" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/1Px2H-ZNAXc" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/FjePwtMW_jA" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/aBuT_NpL4kM" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/bpeEpWjvG50" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/PbeylmdToTs" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/BbDh_D9NOAc" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/dZleU5ZUDAo" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/N1gW3lZx_4I" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/RHk11VC256Y" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/Se39Hv2_FzM" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/ze6pUWYfAvY" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/EO_6mXn9szs" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/WFY1D61ZOV0" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/IQeeRDA6T94" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/fvUETQWW34Y" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/KGI1PiPN-q4" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/p3R5yXcJdX4" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/q44atF--01U" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/H3ajZU-w1Mk" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/yZhWIgH-wqs" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/tVN2lZQV2_M" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/XHDRIk0UL0w" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/Zl53W-m0wTM" },
      { "title": "Lecture 31", "url": "https://www.youtube.com/embed/hhLxKrIj5b4" },
      { "title": "Lecture 32", "url": "https://www.youtube.com/embed/WPQzDvdJQak" },
      { "title": "Lecture 33", "url": "https://www.youtube.com/embed/K8fyaYIGtBE" },
      { "title": "Lecture 34", "url": "https://www.youtube.com/embed/IqiClz6TEiM" },
      { "title": "Lecture 35", "url": "https://www.youtube.com/embed/hezQFC6RJjs" },
      { "title": "Lecture 36", "url": "https://www.youtube.com/embed/LLxVhlleHRM" },
      { "title": "Lecture 37", "url": "https://www.youtube.com/embed/csb-IQN_pqU" },
      { "title": "Lecture 38", "url": "https://www.youtube.com/embed/FgILOHipMtw" },
      { "title": "Lecture 39", "url": "https://www.youtube.com/embed/D0hzgpe5L9s" },
      { "title": "Lecture 40", "url": "https://www.youtube.com/embed/Wr6MNW6itqo" }
    ]
  },
  {
    "title": "JEE Maths Playlist 2 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLTa2m6WeLW__n4j6kuZUVOA7hyljFKG6d",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/AVjdJITX0Nc" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/obx33lta9P4" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/Ui0P-tOC-f0" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/pouyY30rSHo" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/IKZ_2Z2OOBQ" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/--k01m3f5Cw" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/7HbfPG8pVhs" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/2DC7cdv43Ao" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/ryAw6vipopk" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/mjoCuNKUzB4" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/aSAg23ixuWE" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/2eOXSPy1MuE" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/4vagx7oH87k" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/aIjPAFSjRcI" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/0DJXH0ql7BI" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/JdHwa70kY3s" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/qcDGzbWSTjo" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/o07B71pxaBo" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/EJtgkGdqOgY" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/jUxPvBZAK_4" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/56Odj-FzH18" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/PTO6XHJfFU8" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/yMiEhnxQe8Y" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/dgUEfZohNJU" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/UI_SOsUZBJE" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/FJia0zLEq4U" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/Me9E0PFbuGQ" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/feBdaVYlkNs" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/kHj73PtXHQE" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/yZhWIgH-wqs" },
      { "title": "Lecture 31", "url": "https://www.youtube.com/embed/H3ajZU-w1Mk" },
      { "title": "Lecture 32", "url": "https://www.youtube.com/embed/FZJt1h-gO4w" },
      { "title": "Lecture 33", "url": "https://www.youtube.com/embed/mcMHaUuhe6o" },
      { "title": "Lecture 34", "url": "https://www.youtube.com/embed/UNOBGZjYiFk" },
      { "title": "Lecture 35", "url": "https://www.youtube.com/embed/mb_ZpNpL4Go" },
      { "title": "Lecture 36", "url": "https://www.youtube.com/embed/v8qnbEQulmA" },
      { "title": "Lecture 37", "url": "https://www.youtube.com/embed/vMGMYl00kJI" }
    ]
  },
  {
    "title": "JEE Maths Playlist 3 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLTa2m6WeLW__zL1AoV8uEG13xiQMj2RU8",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/j1pDmQJ0wOY" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/nfPvo7p-8t0" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/F0eIeAYiUUM" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/GNtYHAk_C4s" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/Q1AMRktu4pc" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/V3PYBhJS0Po" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/0Bul5m9fN_8" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/AmUO2o9NOYk" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/WvmEDNxgVxg" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/KUu18_pkvbk" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/C3DS0tqK2TY" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/BPgL5Xrp1LA" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/lkAPODbXnS0" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/Bk6PQ6huy68" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/Sh6yppz4nzs" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/HkBKPCNFZ4k" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/QS59lEJgPb8" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/u4Fu2PcRSo4" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/_P2GRAVyk_Q" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/LK0cQmgJsdk" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/MvTfxcM8hHs" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/fdfT1w9rVJQ" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/ct-vCt9NU08" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/cJceE7-8TBY" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/UJXel5_AOSY" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/GN9uAEisDtM" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/peKwXDIcYss" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/iaK4ukVmFvc" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/yP0EKKN0zys" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/7_ZpO1hneXk" },
      { "title": "Lecture 31", "url": "https://www.youtube.com/embed/TQX02-rVCsA" }
    ]
  },
  {
    "title": "JEE Maths Playlist 4 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLTa2m6WeLW_9ka56IJq29mHC07x1j6iIz",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/HEbA_ffeycs" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/13oos03ImGw" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/paNnEHzOfJw" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/hs2_sgEBH30" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/aSy8d4Pbhsw" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/oULeXX4C-oY" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/sgplovRKGJQ" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/UOTNDT9gAQM" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/k6GOnOk4C8k" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/5ji1y2zXcDM" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/zKX-0GoqQow" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/e2l7G25rvqE" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/n7x_TgIt8-0" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/TuBIHZeGSig" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/i5kmKTIbMjM" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/-RYCBXyNfnw" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/t4rV7mfFILI" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/kGLiGAlxocQ" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/vlcoPaJkXN4" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/VlnnqgekQBs" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/eNzhIrJvhCI" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/x1vQ7Lt9s_c" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/ppZfoTxgivM" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/Qw9b25D6Pro" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/Jn5kvM5CPkU" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/iUCypO9QK2A" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/6FFBRPT5o-U" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/T2acOeyHLhg" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/sLiECxCi36Y" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/lpoKizmTvmo" },
      { "title": "Lecture 31", "url": "https://www.youtube.com/embed/FxIohVXV9HQ" },
      { "title": "Lecture 32", "url": "https://www.youtube.com/embed/6RSccpi2w2Q" },
      { "title": "Lecture 33", "url": "https://www.youtube.com/embed/v-U_-LGpUNo" },
      { "title": "Lecture 34", "url": "https://www.youtube.com/embed/R0hkx1qHNVg" },
      { "title": "Lecture 35", "url": "https://www.youtube.com/embed/lpa7iiRVPy4" },
      { "title": "Lecture 36", "url": "https://www.youtube.com/embed/Y39hNNAL5Rg" },
      { "title": "Lecture 37", "url": "https://www.youtube.com/embed/BKPpfNPckhk" },
      { "title": "Lecture 38", "url": "https://www.youtube.com/embed/Q7LCTuL8VSM" },
      { "title": "Lecture 39", "url": "https://www.youtube.com/embed/GUhsxqKCB1c" },
      { "title": "Lecture 40", "url": "https://www.youtube.com/embed/AkGUhKunI3k" },
      { "title": "Lecture 41", "url": "https://www.youtube.com/embed/3MoFRvQpGI4" },
      { "title": "Lecture 42", "url": "https://www.youtube.com/embed/HfOSeihmJ34" },
      { "title": "Lecture 43", "url": "https://www.youtube.com/embed/DhL-fSgc4ZQ" },
      { "title": "Lecture 44", "url": "https://www.youtube.com/embed/HMW-cawtd_k" },
      { "title": "Lecture 45", "url": "https://www.youtube.com/embed/kCxEfhN0YhY" },
      { "title": "Lecture 46", "url": "https://www.youtube.com/embed/7ovfXBsHVqM" },
      { "title": "Lecture 47", "url": "https://www.youtube.com/embed/MPhdM8Z0KPc" },
      { "title": "Lecture 48", "url": "https://www.youtube.com/embed/aa7ysY34JkI" }
    ]
  },
  // ==========================================
  // NEW PLAYLISTS
  // ==========================================
  {
    "title": "Overall Playlist",
    "folders": ["LECTURES", "Overall"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLjvx7xqdpePJD6xrZkipYKAgTioEVsjKu",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/_d0XU35l5jY" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/lKgWBOMWdVU" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/pg2FdPiWeCk" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/3vkFbQxEYqE" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/JJMhkssd4GQ" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/Qbb6H6MhmRc" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/t_2p18RSLXQ" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/EwOMzB63gBI" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/xF9ysyykedw" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/Q8Rujg2Mkio" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/t7-G5GEfQXI" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/IySVKH_OttE" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/0Ro_F6Af0Zg" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/gwC-whA3M3g" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/LIp4AZu3P0g" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/4ioZfE3kGMg" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/gf75PPW10oI" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/MqeFMKAf5x8" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/NKO1Szf4otc" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/qx-CMGn2ud4" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/ie81MM1V4mE" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/lllAWLu5mso" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/1RdDchv2j_o" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/2qGiA1vKwjg" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/YmQvWuXsNhs" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/XBMDnZPLd90" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/JcEaz2o0sL4" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/2fhxJ9ukudY" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/H_9Pl8HeZ-o" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/Wzi1hBDiyVo" },
      { "title": "Lecture 31", "url": "https://www.youtube.com/embed/3Wmsf3lI73Y" },
      { "title": "Lecture 32", "url": "https://www.youtube.com/embed/X1_c_4JaNwU" },
      { "title": "Lecture 33", "url": "https://www.youtube.com/embed/UTUyY5a9G3Y" },
      { "title": "Lecture 34", "url": "https://www.youtube.com/embed/FXJO4GYTmXI" },
      { "title": "Lecture 35", "url": "https://www.youtube.com/embed/5Tb_8wHchbU" },
      { "title": "Lecture 36", "url": "https://www.youtube.com/embed/MWJdpWvwhwc" },
      { "title": "Lecture 37", "url": "https://www.youtube.com/embed/_xOTxiWGGpI" },
      { "title": "Lecture 38", "url": "https://www.youtube.com/embed/jka_UoZPqHs" },
      { "title": "Lecture 39", "url": "https://www.youtube.com/embed/lauuB4VKWw4" },
      { "title": "Lecture 40", "url": "https://www.youtube.com/embed/vHIhXfilkpg" },
      { "title": "Lecture 41", "url": "https://www.youtube.com/embed/sdnEI-mpV4Y" },
      { "title": "Lecture 42", "url": "https://www.youtube.com/embed/U7xuWZaYJ0M" }
    ]
  },
  {
    "title": "New Chemistry Playlist",
    "folders": ["LECTURES", "Chemistry", "New Playlist"],
    "url": "https://www.youtube.com/embed/videoseries?list=PLMttXSB2G2YPzjsMNNaeDoL8eKYPf-qEm",
    "playlist": [
      { "title": "Lecture 1", "url": "https://www.youtube.com/embed/uMWwASLGsPs" },
      { "title": "Lecture 2", "url": "https://www.youtube.com/embed/GRxoVwanRlk" },
      { "title": "Lecture 3", "url": "https://www.youtube.com/embed/5PdbKTtfIY8" },
      { "title": "Lecture 4", "url": "https://www.youtube.com/embed/q_0r4jHwnHs" },
      { "title": "Lecture 5", "url": "https://www.youtube.com/embed/CdZ3NKWS4mI" },
      { "title": "Lecture 6", "url": "https://www.youtube.com/embed/cxbSjezLIZw" },
      { "title": "Lecture 7", "url": "https://www.youtube.com/embed/i5l7TBnZ_Js" },
      { "title": "Lecture 8", "url": "https://www.youtube.com/embed/rH7LapTGFvQ" },
      { "title": "Lecture 9", "url": "https://www.youtube.com/embed/Kd4150Cwv_E" },
      { "title": "Lecture 10", "url": "https://www.youtube.com/embed/Jt7Rlad12Yk" },
      { "title": "Lecture 11", "url": "https://www.youtube.com/embed/Dt_88sinQCY" },
      { "title": "Lecture 12", "url": "https://www.youtube.com/embed/qtvR27V61-k" },
      { "title": "Lecture 13", "url": "https://www.youtube.com/embed/aY-g8J6y22E" },
      { "title": "Lecture 14", "url": "https://www.youtube.com/embed/hjo4JTcT_CU" },
      { "title": "Lecture 15", "url": "https://www.youtube.com/embed/xQM9Pdrs9Oc" },
      { "title": "Lecture 16", "url": "https://www.youtube.com/embed/Yr-lO6vu6xg" },
      { "title": "Lecture 17", "url": "https://www.youtube.com/embed/4zMd6oulWa0" },
      { "title": "Lecture 18", "url": "https://www.youtube.com/embed/qx5iy82Im-k" },
      { "title": "Lecture 19", "url": "https://www.youtube.com/embed/a23kIVvWiuE" },
      { "title": "Lecture 20", "url": "https://www.youtube.com/embed/-y5INTc3Wug" },
      { "title": "Lecture 21", "url": "https://www.youtube.com/embed/HlyG7tz2zBc" },
      { "title": "Lecture 22", "url": "https://www.youtube.com/embed/BDW_xe6JjaU" },
      { "title": "Lecture 23", "url": "https://www.youtube.com/embed/MvnyFuq3yLY" },
      { "title": "Lecture 24", "url": "https://www.youtube.com/embed/YdiD6deJCYg" },
      { "title": "Lecture 25", "url": "https://www.youtube.com/embed/W75q96Fcsd8" },
      { "title": "Lecture 26", "url": "https://www.youtube.com/embed/hUMVET4jE1A" },
      { "title": "Lecture 27", "url": "https://www.youtube.com/embed/JTC2xUNhChk" },
      { "title": "Lecture 28", "url": "https://www.youtube.com/embed/hOpMvRFDSmI" },
      { "title": "Lecture 29", "url": "https://www.youtube.com/embed/d4464t6ssCw" },
      { "title": "Lecture 30", "url": "https://www.youtube.com/embed/AiiVsMrujWc" },
      { "title": "Lecture 31", "url": "https://www.youtube.com/embed/dSkvQBNT9NA" },
      { "title": "Lecture 32", "url": "https://www.youtube.com/embed/Cw7bjKGU75o" },
      { "title": "Lecture 33", "url": "https://www.youtube.com/embed/TPF36JjH0ko" },
      { "title": "Lecture 34", "url": "https://www.youtube.com/embed/20Yt_P7TBVg" },
      { "title": "Lecture 35", "url": "https://www.youtube.com/embed/z2-EeL9Qvf4" },
      { "title": "Lecture 36", "url": "https://www.youtube.com/embed/78AbMcGOdYo" },
      { "title": "Lecture 37", "url": "https://www.youtube.com/embed/qzFtiCIf9Ck" },
      { "title": "Lecture 38", "url": "https://www.youtube.com/embed/WM1OQOM3QW0" }
    ]
  }
];
